//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplaudoApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Artist
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Artist()
        {
            this.Concerts = new HashSet<Concert>();
        }
    
        public long ArtistId { get; set; }
        public string ArtistFirstName { get; set; }
        public string ArtistLastName { get; set; }
        public string ArtistNickName { get; set; }
        public string EmailAddress { get; set; }
        public string Password { get; set; }
        public string VCode { get; set; }
        public string PhotoLink { get; set; }
        public Nullable<int> ArtistTypeId { get; set; }
        public string Spotify { get; set; }
        public string YouTube { get; set; }
        public string iTunes { get; set; }
        public string SoundCloud { get; set; }
        public string LinkedIn { get; set; }
        public string Website { get; set; }
        public string Bio { get; set; }
        public Nullable<long> CountryId { get; set; }
    
        public virtual ArtistType ArtistType { get; set; }
        public virtual Country Country { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Concert> Concerts { get; set; }
    }
}
