//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplaudoApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Artist
    {
        public long ArtistId { get; set; }
        public string ArtistFirstName { get; set; }
        public string ArtistLastName { get; set; }
        public string ArtistNickName { get; set; }
        public string EmailAddress { get; set; }
        public string Password { get; set; }
        public string VCode { get; set; }
    }
}
